[[modules]]
name	= "howl.sms"
class	= "TwilioSMS"

[[accounts]]
name	= "sms"
module	= "twilio"
account	= ""
token	= ""
number	= ""

[[accounts]]
name	= "bar"
module	= "mock"

[options]
[options.editor]
path	= "vim"
mode	= "file"
