[[modules]]
name	= "howl.sms"
class	= "TwilioSMS"

[[accounts]]
name	= "sms"
module	= "howl.sms"
params.account	= ""
params.token	= ""
params.number	= ""

[options]
[options.editor]
path	= "vim"
mode	= "file"
